fix(GUI): all copy/edit buttons visible without hover
Nault/Nault pull request #130
Opened 2020-08-05 14:12 UTC by Joohansson

Copy address buttons was only visible on hover which was not only annoying but also impossible to use on mobile
- Removed all elements containing uk-hidden-hover

Fixes #124 and #111 

Question: Is this ok UI-wise or too many visible buttons in tables, etc.? It's ok IMO.

2020-08-05 16:19 UTC, keerifox commented
i would move the buttons as close as possible to the text they are related to

e.g. it's good on the receive page
![image](https://user-images.githubusercontent.com/29272208/89437532-3a545580-d737-11ea-875e-bc6b1e7728ff.png)

but on the account page both buttons are far from account label/address they apply to
![image](https://user-images.githubusercontent.com/29272208/89437584-4c35f880-d737-11ea-9d61-eb521824fca8.png)


it's a good start though, much better than hidden buttons!

2020-08-05 16:21 UTC, keerifox approved these changes

2020-08-05 17:28 UTC, BitDesert requested changes
I would move the buttons always right after the text which is copied (e.g. address). Otherwise you don't know to which text the copy button belongs to.

2020-08-06 08:54 UTC, Joohansson commented
Did some tightening of the positions. Now the edit button also switches place if there is an account label.

![image](https://user-images.githubusercontent.com/2406720/89510758-4856b480-d7d1-11ea-8a0d-2159d917cead.png)
-------------
![image](https://user-images.githubusercontent.com/2406720/89510797-57d5fd80-d7d1-11ea-8c29-86edb80f09c5.png)
-------------
![image](https://user-images.githubusercontent.com/2406720/89511548-59ec8c00-d7d2-11ea-836a-ec56ab484415.png)
-------------
![image](https://user-images.githubusercontent.com/2406720/89511715-8f917500-d7d2-11ea-8901-fc05b2523d04.png)

I left the space in the account overview because the buttons would not align otherwise and it would look bad I think.
![image](https://user-images.githubusercontent.com/2406720/89512028-f151df00-d7d2-11ea-80ba-f46f2f23dcc0.png)

2020-08-06 13:11 UTC, keerifox commented
![image](https://user-images.githubusercontent.com/29272208/89535522-0f750a80-d7e6-11ea-8949-70ccb9fbe6da.png)

could it say "Account #X" here instead of "Awesome account", when no label is set?
would remove ambiguity from the pencil icon, and make it easier to connect accounts in the sidebar with accounts in the main view

2020-08-06 14:31 UTC, Joohansson commented
> could it say "Account #X" here when no label is set?
> would remove ambiguity from the pencil icon, and make it easier to connect accounts in the sidebar with accounts in the main view

Done!
![image](https://user-images.githubusercontent.com/2406720/89544303-3e00de80-d802-11ea-9230-de6424d5b6d9.png)

2020-08-07 07:30 UTC, merged