Warn for 2%
Nault/Nault pull request #131
Opened 2020-08-05 17:43 UTC by BitDesert

IMO a "warning" for a rep should occur at >2%.
If a rep has ~1.X % this should not trigger a warning.

At the current state this would be better than the current check, as the decentralization get's better these limits can get modified again.

2020-08-05 19:18 UTC, keerifox commented
sounds ok to me, just remember to change 1% to 2% in these files:
change-rep-widget.component.html
representatives.component.html

2020-08-05 19:32 UTC, Joohansson requested changes
As keeri said, please change the text as well so it's not forgotten:

- https://github.com/Nault/Nault/blob/05b9272f46e489a76502e0a29ea8c2b4e8894036/src/app/components/representatives/representatives.component.html#L37
- https://github.com/Nault/Nault/blob/05b9272f46e489a76502e0a29ea8c2b4e8894036/src/app/components/change-rep-widget/change-rep-widget.component.html#L56

2020-08-05 19:53 UTC, aleksre commented
Would maybe be a good idea to make these global constants and reference them in both code and texts so they can be easily adjusted as decentralization improves.

2020-08-05 19:59 UTC, BitDesert commented
I will port that to the environtment with #76 and just fix it in the code for now.

2020-08-06 07:56 UTC, Joohansson approved these changes

2020-08-06 09:18 UTC, merged