New rep summary page
Nault/Nault pull request #262
Opened 2021-01-20 15:41 UTC by keerifox

before:

![image](https://user-images.githubusercontent.com/29272208/105192316-dfb98500-5b2f-11eb-9ec4-dd39e1707339.png)

after:

![image](https://user-images.githubusercontent.com/29272208/105196438-86ebeb80-5b33-11eb-9e15-022d6af3d2ed.png)

i wasn't able to show account indexes here e.g. `Account #7`, as the index isn't part of the account object. perhaps someone could implement that later on

\-

reps book also undertook some changes, mostly to provide clarity and avoid possible confusion with the list of used reps

before:

![image](https://user-images.githubusercontent.com/29272208/105193174-5b1b3680-5b30-11eb-8390-d84ec1d45cfc.png)

after:

![image](https://user-images.githubusercontent.com/29272208/105193358-666e6200-5b30-11eb-948e-88792680334f.png)

2021-01-21 07:19 UTC, Joohansson approved these changes
Nice work, looks good!

2021-01-22 18:48 UTC, BitDesert requested changes
I don't know if the labels are a bit too flashy when hovering them.
They change colors often and the change is not consistent (rep changes from purple to grey with purple border, account changes from grey to solid blue).

Additionally it would be great when the list below would reset when you click on a different account/rep. Currently it just adds it to the list.

2021-01-22 19:46 UTC, keerifox commented
> I don't know if the labels are a bit too flashy when hovering them.
> They change colors often and the change is not consistent (rep changes from purple to grey with purple border, account changes from grey to solid blue).

this is intentional, accounts and reps have their own distinct styles and are presented as is to be consistent with how they look throughout the rest of the application and to accent color only on representatives rather than reps and accounts both


> Additionally it would be great when the list below would reset when you click on a different account/rep. Currently it just adds it to the list.

that's the old behavior: you click on everything that you wish to change, and it is added to the list allowing you to change several reps or accounts at once

2021-01-22 23:18 UTC, BitDesert approved these changes
Alright, thanks @keerifox !

2021-01-22 23:19 UTC, merged