Implemented wallet sweeper
Nault/Nault pull request #42
Opened 2020-07-06 16:27 UTC by Joohansson

I would like some help battle testing this @BitDesert . The core processing code is pretty much the same as the one I built for https://tools.nanos.cc/?tool=sweep but using the features of Nault, like the PoW source and minimum receive from the settings. It probably needs some design love but it's working.

An easy method for testing this is to generate a seed here: https://tools.nanos.cc/?tool=seed
Then using the QR on the account field and try sending some nano to different indexes and derivation method from Natrium. Then testing with either seed, private key or mnemonic on the sweeper. This is also a perfect simulation of a ledger passphrase recover if using the BIP39/44.

Solves #38 and #29 

![1](https://user-images.githubusercontent.com/2406720/86616299-f0504680-bfb5-11ea-8575-57f61d2760fc.PNG)

2020-07-06 17:25 UTC, BitDesert requested changes
Some things I would change:
- Embed the GUI in a `uk-card` like the send dialog
- Remove the "Destination Account field" as you would use it only with accounts setup in Nault
- "Set Min" is basically a "reset" button, so we might call it that way
- "Set Max" sets currently both Start and End pretty high but 100 apart. Why?
- There is a third "Set Max" button that looks the same but just sets "Max TX" back to 100 (which is the default). So it's functionality is the same as a "Reset" button
- The message "An account was swept and funds transferred to the destination!" does not disappear, maybe include the account name as well
- A spinning animation like a the "Send" page would be cool, so you see that it's "doing something"
- There is no "Success" message when it's done

Would it be better to set the type of the secret in a dropdown? Or just let it fiddle out itself?

2020-07-06 21:07 UTC, Joohansson commented
New design
![image](https://user-images.githubusercontent.com/2406720/86644051-7d5ac600-bfdd-11ea-8dda-6b4b7b4b000f.png)

2020-07-07 10:36 UTC, BitDesert approved these changes
Lookin good 👍

2020-07-07 11:38 UTC, NiFNi reviewed
I like the way this works! The UI looks good for me aswell. Some small things came to my mind when looking at the sources. I added those as comments on the files :) Do whatever you want with that :P

2020-07-07 11:38 UTC, NiFNi commented on src/app/components/sweeper/sweeper.component.html
> +                    <option *ngFor="let account of accounts" [value]="account.id">{{ account.id }}</option>
Shouldn't this use the alias set for the account if there is one?

2020-07-07 11:38 UTC, NiFNi commented on src/app/components/sweeper/sweeper.component.html
> +                <label class="uk-form-label">Local Destination<span uk-icon="icon: info;" uk-tooltip title="Local accounts that can be used as destination for the swept funds. Make sure you are able
Shouldn't the label be assiciated with the input field via the for attribute? Same applies to the other labels.
See here for more information: https://stackoverflow.com/questions/12894169/what-is-the-html-for-attribute-in-label

2020-07-07 11:38 UTC, NiFNi commented on src/app/services/util.service.ts
> +  if (isnum && String(val).slice(-1) !== '.') {
can be simplified to 
```
return isnum && String(val).slice(-1) !== '.'
```

2020-07-07 11:38 UTC, NiFNi commented on src/app/services/util.service.ts
> +    return true
Can be simplified to 
```
return re.test(h)
```

2020-07-08 07:10 UTC, Joohansson commented on src/app/services/util.service.ts
> +  if (isnum && String(val).slice(-1) !== '.') {
Thanks nifni, I will make some changes before I merge this PR

2020-07-08 12:20 UTC, merged